### ISSUE TITLE
Not booting on AMD CPUs

### ISSUE THREAD

**Issue by piotr25691** [hewol/aerOS#32]
It has come to my attention, that aerOS will not commence to boot on an AMD CPU.

Here are the possible outcomes of trying anyways:

- [!!!!!!] Failed to start up manager.
- The boot process hangs on "Waiting for kernel time to be synchronized" / "Rebuilding dynamic linker cache"

What's the issue? We shall see.

**Comment by debarkak** [comment]
@piotr25691 the `amd-ucode` boot is present in both `grub` (efi boot) and `syslinux` (mbr boot) however it seems that the `amd-ucode` package is missing, and using the `intel-ucode` instead causing several issues in amd, i dont have a amd pc, but we have to figure this out.

**Comment by debarkak** [comment]
@piotr25691 so i switched priority's aka intel then amd, to amd then intel, on commit https://github.com/hewol/aerOS/commit/a0188055921a3f1f2baadb5378b03113cd5f3091 . i will build another aerOS and make sure to test it out, it will be on my home directory in solar.

**Comment by piotr25691** [comment]
fixed in #34

`amd-ucode` and wayland boot in gdm fix aerOS
